@testset "model_utils.jl" begin
    @testset "value_iterator_from_chain" begin
        @testset "$model" for model in DynamicPPL.TestUtils.DEMO_MODELS
            # Check that the values generated by value_iterator_from_chain
            # match the values in the original chain
            chain = make_chain_from_prior(model, 10)
            for (i, d) in enumerate(value_iterator_from_chain(model, chain))
                for vn in keys(d)
                    val = DynamicPPL.getvalue(d, vn)
                    # Because value_iterator_from_chain groups varnames with
                    # the same parent symbol, we have to ungroup them here
                    for vn_leaf in DynamicPPL.varname_leaves(vn, val)
                        val_leaf = DynamicPPL.getvalue(d, vn_leaf)
                        @test val_leaf == chain[i, Symbol(vn_leaf), 1]
                    end
                end
            end
        end
    end
end
