module DynamicPPLBridgeStanExt

using Bijectors
using BridgeStan
using Distributions
using DynamicPPL
using Random
using Base.Libc.Libdl: dlsym
using LinearAlgebra: dot

const _WRITER_START = "  template <typename RNG, typename VecR, typename VecI, typename VecVar,"
const _PARAMETER_END = "      if (stan::math::logical_negation("
const _SUPPORTED_STAN_RELEASES = ((2, 39),)

function _warn_untested_versions(source::String)
    version_match = match(r"Code generated by stanc v([^\s]+)", source)
    if isnothing(version_match)
        @warn "Could not determine the stanc3 version from the generated model"
        return nothing
    end
    stanc_version = tryparse(VersionNumber, only(version_match.captures))
    if isnothing(stanc_version)
        @warn "Could not parse the stanc3 version from the generated model"
    elseif (stanc_version.major, stanc_version.minor) ∉ _SUPPORTED_STAN_RELEASES
        @warn "The generated-model patch supports Stan 2.39.x; found $stanc_version"
    end
end

function _parameter_writer(source::String)
    writer = findfirst("write_array_impl(", source)
    isnothing(writer) && error("stanc3 output has no `write_array_impl`")
    start = findprev(_WRITER_START, source, first(writer))
    isnothing(start) && error("unsupported stanc3 `write_array_impl` signature")
    stop = findnext(_PARAMETER_END, source, last(writer))
    isnothing(stop) && error("unsupported stanc3 parameter writer")

    prefix = source[first(start):(first(stop) - 1)]
    prefix = replace(prefix, "write_array_impl" => "write_parameters_ad_impl"; count=1)
    prefix = replace(
        prefix,
        r"stan::require_vector_like_vt<std::is_floating_point,\s*VecR>" => "stan::require_vector_like_t<VecR>",
        r"stan::require_vector_vt<std::is_floating_point,\s*VecVar>" => "stan::require_vector_t<VecVar>",
        "using local_scalar_t__ = double;" => "using local_scalar_t__ = stan::scalar_type_t<VecR>;",
    )
    # Tuple parameter locals contain nested `double` types instead of the scalar alias.
    prefix = replace(prefix, r"\bdouble\b" => "local_scalar_t__")
    return prefix * """
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
"""
end

const _CPP_API = raw"""

#if defined(_WIN32)
#define DYNAMICPPL_BS_PUBLIC __declspec(dllexport)
#else
#define DYNAMICPPL_BS_PUBLIC __attribute__((visibility("default")))
#endif

namespace dynamicppl_bridgestan {

inline void set_error(char** error, const char* message) {
  if (error == nullptr) return;
  const std::size_t size = std::strlen(message) + 1;
  *error = static_cast<char*>(std::malloc(size));
  std::memcpy(*error, message, size);
}

inline std::unique_ptr<stan_model> make_model(const char* data,
                                               unsigned int seed) {
  if (data == nullptr || data[0] == '\0') {
    stan::io::empty_var_context context;
    return std::make_unique<stan_model>(context, seed, nullptr);
  }
  std::istringstream stream(data);
  stan::json::json_data context(stream);
  return std::make_unique<stan_model>(context, seed, nullptr);
}

struct transform {
  std::unique_ptr<stan_model> model;
  stan::rng_t rng;

  transform(const char* data, unsigned int seed)
      : model(make_model(data, seed)),
        rng(stan::services::util::create_rng(seed, 0)) {}
};

template <typename Vec>
auto constrain(transform* transform, Vec& input, int size) {
  Eigen::Matrix<stan::scalar_type_t<Vec>, Eigen::Dynamic, 1> output(size);
  std::vector<int> integers;
  transform->model->write_parameters_ad_impl(
      transform->rng, input, integers, output, false, false, nullptr);
  return output;
}

}  // namespace dynamicppl_bridgestan

extern "C" {

DYNAMICPPL_BS_PUBLIC void dynamicppl_bs_free_error(char* error) {
  std::free(error);
}

DYNAMICPPL_BS_PUBLIC void* dynamicppl_bs_transform_construct(
    const char* data, unsigned int seed, char** error) {
  try {
    return new dynamicppl_bridgestan::transform(data, seed);
  } catch (const std::exception& e) {
    dynamicppl_bridgestan::set_error(error, e.what());
    return nullptr;
  }
}

DYNAMICPPL_BS_PUBLIC void dynamicppl_bs_transform_destruct(void* pointer) {
  delete static_cast<dynamicppl_bridgestan::transform*>(pointer);
}

DYNAMICPPL_BS_PUBLIC int dynamicppl_bs_param_constrain_jvp(
    void* pointer, const double* u, const double* du, int n, int m,
    double* result, char** error) {
  try {
    auto* transform = static_cast<dynamicppl_bridgestan::transform*>(pointer);
    Eigen::Map<const Eigen::VectorXd> input(u, n);
    Eigen::Map<const Eigen::VectorXd> tangent(du, n);
    if (m == 0) return 0;
    auto constrain = [&](auto& input_ad) {
      return dynamicppl_bridgestan::constrain(transform, input_ad, m);
    };
    // The unit-vector fvar overload does not propagate arbitrary tangents.
    Eigen::VectorXd value;
    Eigen::MatrixXd jacobian;
    stan::math::jacobian(constrain, input, value, jacobian);
    Eigen::Map<Eigen::VectorXd>(result, m) = jacobian * tangent;
    return 0;
  } catch (const std::exception& e) {
    dynamicppl_bridgestan::set_error(error, e.what());
    return 1;
  }
}

DYNAMICPPL_BS_PUBLIC int dynamicppl_bs_param_constrain_vjp(
    void* pointer, const double* u, const double* cotangent, int n, int m,
    double* result, char** error) {
  try {
    auto* transform = static_cast<dynamicppl_bridgestan::transform*>(pointer);
    Eigen::Map<const Eigen::VectorXd> input(u, n);
    Eigen::Map<const Eigen::VectorXd> output_cotangent(cotangent, m);
    auto objective = [&](auto& input_ad) {
      auto output_ad = dynamicppl_bridgestan::constrain(transform, input_ad, m);
      return stan::math::dot_product(output_ad, output_cotangent);
    };
    double value;
    Eigen::VectorXd gradient;
    stan::math::gradient(objective, input, value, gradient);
    Eigen::Map<Eigen::VectorXd>(result, n) = gradient;
    return 0;
  } catch (const std::exception& e) {
    dynamicppl_bridgestan::set_error(error, e.what());
    return 1;
  }
}

}  // extern "C"
"""

function _patch_model(header::String)
    source = read(header, String)
    _warn_untested_versions(source)
    helper = _parameter_writer(source)
    writer = findfirst("write_array_impl(", source)::UnitRange
    start = findprev(_WRITER_START, source, first(writer))::UnitRange
    source = source[begin:(first(start) - 1)] * helper * source[first(start):end]

    source = replace(
        source,
        "#include <stan/model/model_header.hpp>" => "#include <stan/model/model_header.hpp>\n#include <stan/io/empty_var_context.hpp>\n#include <stan/io/json/json_data.hpp>\n#include <cstdlib>\n#include <cstring>\n#include <sstream>";
        count=1,
    )
    model_alias = findfirst("\nusing stan_model = ", source)
    isnothing(model_alias) && error("stanc3 output has no `stan_model` alias")
    semicolon = findnext(';', source, last(model_alias))
    isnothing(semicolon) && error("invalid stanc3 `stan_model` alias")
    source = source[begin:semicolon] * _CPP_API * source[(semicolon + 1):end]
    write(header, source)
    return header
end

function _run_build(command::Cmd)
    output = IOBuffer()
    errors = IOBuffer()
    success(pipeline(command; stdout=output, stderr=errors)) && return nothing
    return error(
        "Stan compilation failed:\n$(String(take!(output)))\n$(String(take!(errors)))"
    )
end

function _compile(source::AbstractString; stanc_args=String[], make_args=String[])
    directory = mktempdir()
    stan_file = joinpath(directory, "model.stan")
    header = joinpath(directory, "model.hpp")
    library = joinpath(directory, "model_model.so")
    write(stan_file, source)

    bridgestan = BridgeStan.get_bridgestan_path()
    make = get(ENV, "MAKE", "make")
    stancflags = join(["--include-paths=$directory"; stanc_args], " ")
    _run_build(Cmd(`$make $make_args $("STANCFLAGS=$stancflags") $header`; dir=bridgestan))
    _patch_model(header)
    _run_build(Cmd(`$make $make_args $("STANCFLAGS=$stancflags") $library`; dir=bridgestan))
    return library
end

mutable struct StanTransform <: DynamicPPL._StanDifferentiableFunction
    model::BridgeStan.StanModel
    pointer::Ptr{Cvoid}

    function StanTransform(model::BridgeStan.StanModel)
        error_ref = Ref{Cstring}(C_NULL)
        pointer = @ccall $(dlsym(model.lib, :dynamicppl_bs_transform_construct))(
            model.data::Cstring, model.seed::Cuint, error_ref::Ref{Cstring}
        )::Ptr{Cvoid}
        pointer == C_NULL && _throw_error(model, error_ref)
        transform = new(model, pointer)
        finalizer(transform) do value
            if value.pointer != C_NULL
                @ccall $(dlsym(value.model.lib, :dynamicppl_bs_transform_destruct))(
                    value.pointer::Ptr{Cvoid}
                )::Cvoid
                value.pointer = C_NULL
            end
        end
        return transform
    end
end

struct StanLogDensity <: DynamicPPL._StanDifferentiableFunction
    model::BridgeStan.StanModel
end

struct StanDistribution <: Distributions.ContinuousMultivariateDistribution
    transform::StanTransform
    dimension::Int

    function StanDistribution(transform::StanTransform)
        return new(transform, Int(BridgeStan.param_unc_num(transform.model)))
    end
end

const _STAN_DISTRIBUTION_CACHE = Dict{Tuple,StanDistribution}()
const _STAN_DISTRIBUTION_CACHE_LOCK = ReentrantLock()

function _throw_error(model::BridgeStan.StanModel, error_ref::Ref{Cstring})
    message = unsafe_string(error_ref[])
    @ccall $(dlsym(model.lib, :dynamicppl_bs_free_error))(error_ref[]::Cstring)::Cvoid
    return error(message)
end

function _check_length(value, expected::Int, name::String)
    return length(value) == expected || throw(
        DimensionMismatch("`$name` has length $(length(value)); expected $expected")
    )
end

"""
    to_distribution(source::AbstractString; data="", seed=204, stanc_args=[], make_args=[])

Compile a Stan program and wrap its joint density for use in a DynamicPPL model.

For `parameters ~ to_distribution(source)`, `parameters` is the flattened constrained
parameter vector in Stan declaration order. DynamicPPL stores the corresponding
unconstrained vector and evaluates the Stan target with its Jacobian adjustment.

`data` is JSON supplied to the Stan model. `seed` initializes BridgeStan's model-construction
RNG; it does not draw model parameters. `stanc_args` and `make_args` are forwarded to the
BridgeStan build. The first call for each combination of these inputs compiles and patches
the generated C++ model; subsequent calls return the cached distribution. A working
BridgeStan toolchain is therefore required. The adapter uses a standard-normal vector only
to initialise the unconstrained coordinates because BridgeStan does not provide a sampler.
"""
function DynamicPPL.to_distribution(
    source::AbstractString;
    data::AbstractString="",
    seed=204,
    stanc_args=String[],
    make_args=String[],
)
    source = String(source)
    data = String(data)
    seed = convert(UInt32, seed)
    stanc_args = map(String, Tuple(stanc_args))
    make_args = map(String, Tuple(make_args))
    key = (source, data, seed, stanc_args, make_args)
    return lock(_STAN_DISTRIBUTION_CACHE_LOCK) do
        return get!(_STAN_DISTRIBUTION_CACHE, key) do
            library = _compile(
                source; stanc_args=collect(stanc_args), make_args=collect(make_args)
            )
            model = BridgeStan.StanModel(library, data, seed; warn=false)
            return StanDistribution(StanTransform(model))
        end
    end
end

Base.length(distribution::StanDistribution) = distribution.dimension

function Distributions.insupport(distribution::StanDistribution, value::AbstractVector)
    return length(value) == length(distribution) && all(isfinite, value)
end

function Distributions.logpdf(distribution::StanDistribution, value::AbstractVector{<:Real})
    _check_length(value, length(distribution), "value")
    return StanLogDensity(distribution.transform.model)(value)
end

function DynamicPPL.init(
    rng::Random.AbstractRNG,
    ::DynamicPPL.VarName,
    distribution::StanDistribution,
    ::DynamicPPL.InitFromPrior,
)
    # Stan exposes a target density but no sampler; this value is only an initial point.
    return DynamicPPL.TransformedValue(
        randn(rng, length(distribution)), DynamicPPL.FixedTransform(distribution.transform)
    )
end

function _stan_assume!!(distribution, vn, template, vi, transformed_value)
    transform = DynamicPPL.get_transform(transformed_value)
    transform isa DynamicPPL.FixedTransform &&
        transform.transform === distribution.transform || error(
        "Stan model parameters must retain their fixed unconstrained-to-constrained transform",
    )
    u = DynamicPPL.get_internal_value(transformed_value)
    parameters = distribution.transform(u)
    vi = DynamicPPL.accumulate_assume!!(
        vi, u, transformed_value, zero(DynamicPPL.LogProbType), vn, distribution, template
    )
    return parameters, vi
end

function DynamicPPL.tilde_assume!!(
    context::DynamicPPL.InitContext,
    distribution::StanDistribution,
    vn::DynamicPPL.VarName,
    template,
    vi::DynamicPPL.AbstractVarInfo,
)
    transformed_value = DynamicPPL.init(context.rng, vn, distribution, context.strategy)
    vi = DynamicPPL.setindex_with_dist!!(vi, transformed_value, distribution, vn, template)
    return _stan_assume!!(distribution, vn, template, vi, transformed_value)
end

function DynamicPPL.tilde_assume!!(
    ::DynamicPPL.DefaultContext,
    distribution::StanDistribution,
    vn::DynamicPPL.VarName,
    template,
    vi::DynamicPPL.AbstractVarInfo,
)
    transformed_value = DynamicPPL.get_transformed_value(vi, vn)
    return _stan_assume!!(distribution, vn, template, vi, transformed_value)
end

function _stan_constrain(transform::StanTransform, u::AbstractVector{<:Real})
    _check_length(u, Int(BridgeStan.param_unc_num(transform.model)), "u")
    return BridgeStan.param_constrain(transform.model, collect(Float64, u))
end
function DynamicPPL._stan_value(transform::StanTransform, u::AbstractVector{<:Real})
    return _stan_constrain(transform, u)
end

function DynamicPPL._stan_value(logdensity::StanLogDensity, u::AbstractVector{<:Real})
    return BridgeStan.log_density(
        logdensity.model, collect(Float64, u); propto=false, jacobian=true
    )
end

function _stan_jvp(
    transform::StanTransform, u::AbstractVector{<:Real}, du::AbstractVector{<:Real}
)
    n = Int(BridgeStan.param_unc_num(transform.model))
    m = Int(BridgeStan.param_num(transform.model))
    _check_length(u, n, "u")
    _check_length(du, n, "du")
    u_stan = collect(Float64, u)
    du_stan = collect(Float64, du)
    result = Vector{Float64}(undef, m)
    error_ref = Ref{Cstring}(C_NULL)
    status = @ccall $(dlsym(transform.model.lib, :dynamicppl_bs_param_constrain_jvp))(
        transform.pointer::Ptr{Cvoid},
        u_stan::Ptr{Cdouble},
        du_stan::Ptr{Cdouble},
        n::Cint,
        m::Cint,
        result::Ptr{Cdouble},
        error_ref::Ref{Cstring},
    )::Cint
    iszero(status) || _throw_error(transform.model, error_ref)
    return result
end

function _stan_vjp(
    transform::StanTransform, u::AbstractVector{<:Real}, cotangent::AbstractVector{<:Real}
)
    n = Int(BridgeStan.param_unc_num(transform.model))
    m = Int(BridgeStan.param_num(transform.model))
    _check_length(u, n, "u")
    _check_length(cotangent, m, "cotangent")
    u_stan = collect(Float64, u)
    cotangent_stan = collect(Float64, cotangent)
    result = Vector{Float64}(undef, n)
    error_ref = Ref{Cstring}(C_NULL)
    status = @ccall $(dlsym(transform.model.lib, :dynamicppl_bs_param_constrain_vjp))(
        transform.pointer::Ptr{Cvoid},
        u_stan::Ptr{Cdouble},
        cotangent_stan::Ptr{Cdouble},
        n::Cint,
        m::Cint,
        result::Ptr{Cdouble},
        error_ref::Ref{Cstring},
    )::Cint
    iszero(status) || _throw_error(transform.model, error_ref)
    return result
end

function DynamicPPL._stan_value_and_pushforward(
    transform::StanTransform, u, tangents::NTuple
)
    return transform(u), map(du -> _stan_jvp(transform, u, du), tangents)
end

function DynamicPPL._stan_value_and_pullback(
    transform::StanTransform, u, cotangents::NTuple
)
    return transform(u), map(cotangent -> _stan_vjp(transform, u, cotangent), cotangents)
end

function _stan_logdensity_gradient(logdensity::StanLogDensity, u)
    return BridgeStan.log_density_gradient(
        logdensity.model, collect(Float64, u); propto=false, jacobian=true
    )
end

function DynamicPPL._stan_value_and_pushforward(
    logdensity::StanLogDensity, u, tangents::NTuple
)
    value, gradient = _stan_logdensity_gradient(logdensity, u)
    return value, map(tangent -> dot(gradient, tangent), tangents)
end

function DynamicPPL._stan_value_and_pullback(
    logdensity::StanLogDensity, u, cotangents::NTuple
)
    value, gradient = _stan_logdensity_gradient(logdensity, u)
    return value, map(cotangent -> cotangent * gradient, cotangents)
end

const VectorBijectors = Bijectors.VectorBijectors
VectorBijectors.from_linked_vec(::StanDistribution) = VectorBijectors.TypedIdentity()
VectorBijectors.to_linked_vec(::StanDistribution) = VectorBijectors.TypedIdentity()
VectorBijectors.linked_vec_length(distribution::StanDistribution) = length(distribution)
function VectorBijectors.linked_optic_vec(distribution::StanDistribution)
    return VectorBijectors.optic_vec(distribution)
end

end
