module DynamicPPLBridgeStanExtTests

using ADTypes: AutoMooncake
using Bijectors
using BridgeStan
using Distributions: Normal, insupport, logpdf
using DynamicPPL
using ForwardDiff
using LinearAlgebra: dot, norm
using LogDensityProblems
using Mooncake
using Random: Xoshiro
using Test

const BridgeStanExt = Base.get_extension(DynamicPPL, :DynamicPPLBridgeStanExt)

const STAN_SOURCE = """
parameters {
  simplex[3] theta;
  real<lower=0> sigma;
  unit_vector[2] direction;
  tuple(real<lower=0>, simplex[2]) pair;
}
model {
  theta ~ dirichlet(rep_vector(1, 3));
  sigma ~ exponential(1);
}
generated quantities {
  real draw = normal_rng(sigma, 1);
}
"""

const STAN_PARAMETER_TYPES = """
data {
  int<lower=2> K;
}
transformed data {
  real limit = 2;
}
parameters {
  real plain;
  real<lower=0> lower_real;
  real<upper=1> upper_real;
  real<lower=-1, upper=1> bounded_real;
  real<offset=1> offset_real;
  real<multiplier=2> scaled_real;
  real<offset=1, multiplier=2> affine_real;
  real<lower=-limit, upper=limit> data_bounded_real;
  vector[K] plain_vector;
  vector<lower=0>[K] lower_vector;
  vector<upper=1>[K] upper_vector;
  vector<lower=-1, upper=1>[K] bounded_vector;
  vector<offset=1>[K] offset_vector;
  vector<multiplier=2>[K] scaled_vector;
  vector<offset=1, multiplier=2>[K] affine_vector;
  row_vector[K] plain_row_vector;
  row_vector<lower=0>[K] lower_row_vector;
  row_vector<upper=1>[K] upper_row_vector;
  row_vector<lower=-1, upper=1>[K] bounded_row_vector;
  row_vector<offset=1>[K] offset_row_vector;
  row_vector<multiplier=2>[K] scaled_row_vector;
  row_vector<offset=1, multiplier=2>[K] affine_row_vector;
  matrix[K, K] plain_matrix;
  matrix<lower=0>[K, K] lower_matrix;
  matrix<upper=1>[K, K] upper_matrix;
  matrix<lower=-1, upper=1>[K, K] bounded_matrix;
  matrix<offset=1>[K, K] offset_matrix;
  matrix<multiplier=2>[K, K] scaled_matrix;
  matrix<offset=1, multiplier=2>[K, K] affine_matrix;
  ordered[K] ordered_parameter;
  positive_ordered[K] positive_ordered_parameter;
  simplex[K] simplex_parameter;
  unit_vector[K] unit_vector_parameter;
  sum_to_zero_vector[K] zero_sum_vector;
  column_stochastic_matrix[K, K] column_stochastic_parameter;
  row_stochastic_matrix[K, K] row_stochastic_parameter;
  sum_to_zero_matrix[K, K] zero_sum_matrix;
  corr_matrix[K] correlation_parameter;
  cov_matrix[K] covariance_parameter;
  cholesky_factor_corr[K] correlation_cholesky;
  cholesky_factor_cov[K] covariance_cholesky;
  cholesky_factor_cov[K + 1, K] rectangular_covariance_cholesky;
  complex complex_parameter;
  complex_vector[K] complex_vector_parameter;
  complex_row_vector[K] complex_row_vector_parameter;
  complex_matrix[K, K] complex_matrix_parameter;
  array[2, 2] simplex[K] simplex_array;
  tuple(real<lower=0>, array[2] real, tuple(simplex[K], complex)) nested_tuple;
  array[2] tuple(array[2] real, tuple(simplex[K], real)) tuple_array;
  vector[0] empty_vector;
  array[0] real empty_array;
}
transformed parameters {
  real transformed_parameter = 2 * plain;
}
model {
  plain ~ normal(0, 1);
}
generated quantities {
  real draw = normal_rng(transformed_parameter, 1);
}
"""

const STAN_NO_PARAMETERS = """
data {
  real observation;
}
model {
  observation ~ normal(0, 1);
}
"""

const STAN_NO_FREE_PARAMETERS = """
parameters {
  simplex[1] probability;
}
"""

@testset "BridgeStan extension" begin
    @test_throws ErrorException BridgeStanExt._parameter_writer("")
    @test_throws ErrorException BridgeStanExt._unconstrain_writer("")
    @test_logs (:warn, r"Could not determine") BridgeStanExt._warn_untested_versions("")
    @test_logs (:warn, r"supports Stan 2.39.x") BridgeStanExt._warn_untested_versions(
        "// Code generated by stanc v2.40.0"
    )

    distribution = to_distribution(STAN_SOURCE)
    @test to_distribution(STAN_SOURCE) === distribution
    from_prior = DynamicPPL.init(Xoshiro(1), @varname(theta), distribution, InitFromPrior())
    from_uniform = DynamicPPL.init(
        Xoshiro(1), @varname(theta), distribution, InitFromUniform()
    )
    @test from_prior == from_uniform
    u = [0.3, -0.7, 0.2, 0.4, -0.1, 0.5, -0.2]
    du = [-0.2, 0.5, 0.3, -0.1, 0.2, 0.4, -0.3]
    cotangent = [1.2, -0.4, 0.8, 0.1, -0.2, 0.7, 0.3, -0.1, 0.6]
    step = 1e-6

    constrained = distribution.transform(u)
    finite_difference_jvp =
        (distribution.transform(u + step * du) - distribution.transform(u - step * du)) /
        (2 * step)
    finite_difference_vjp = map(eachindex(u)) do index
        direction = zeros(length(u))
        direction[index] = step
        return cotangent' * (
            distribution.transform(u + direction) - distribution.transform(u - direction)
        ) / (2 * step)
    end
    _, (jvp, doubled_jvp) = DynamicPPL._stan_value_and_pushforward(
        distribution.transform, u, (du, 2du)
    )
    _, (vjp,) = DynamicPPL._stan_value_and_pullback(distribution.transform, u, (cotangent,))

    @test length(distribution) == length(constrained)
    @test length(constrained) == length(cotangent)
    @test Bijectors.VectorBijectors.linked_vec_length(distribution) == length(u)
    @test insupport(distribution, constrained)
    @test !insupport(distribution, u)
    @test logpdf(distribution, u) == -Inf
    invalid = copy(constrained)
    invalid[1] = 2
    @test !insupport(distribution, invalid)
    @test logpdf(distribution, invalid) == -Inf
    @test !insupport(distribution, fill(NaN, length(distribution)))
    @test logpdf(distribution, fill(NaN, length(distribution))) == -Inf
    @test norm(constrained[5:6]) ≈ 1
    @test constrained[7] > 0
    @test sum(constrained[8:9]) ≈ 1
    @test norm(jvp - finite_difference_jvp) < 1e-8
    @test doubled_jvp ≈ 2jvp
    @test norm(vjp - finite_difference_vjp) < 1e-8
    @test logpdf(distribution, constrained) ≈ BridgeStan.log_density(
        distribution.transform.model, u; propto=false, jacobian=false
    )
    @test ForwardDiff.gradient(x -> logpdf(distribution, x), constrained) isa
        Vector{Float64}
    @test ForwardDiff.jacobian(distribution.transform, u) * du ≈ jvp
    unconstrain = Bijectors.VectorBijectors.to_linked_vec(distribution)
    canonical_u = unconstrain(constrained)
    @test distribution.transform(canonical_u) ≈ constrained
    @test Bijectors.inverse(unconstrain) === distribution.transform
    _, (unconstrain_jvp,) = DynamicPPL._stan_value_and_pushforward(
        unconstrain, constrained, (jvp,)
    )
    _, (unconstrain_vjp,) = DynamicPPL._stan_value_and_pullback(
        unconstrain, constrained, (du,)
    )
    finite_difference_unconstrain_jvp =
        (
            unconstrain(distribution.transform(u + step * du)) -
            unconstrain(distribution.transform(u - step * du))
        ) / (2 * step)
    @test unconstrain_jvp ≈ finite_difference_unconstrain_jvp
    @test dot(unconstrain_vjp, jvp) ≈ dot(du, unconstrain_jvp)
    constrained_again, logjac = Bijectors.with_logabsdet_jacobian(distribution.transform, u)
    @test constrained_again ≈ constrained
    @test logjac ≈
        BridgeStan.log_density(
        distribution.transform.model, u; propto=false, jacobian=true
    ) - BridgeStan.log_density(
        distribution.transform.model, u; propto=false, jacobian=false
    )

    @model function combined(stan, y)
        theta ~ to_distribution(stan)
        y ~ Normal(theta[1], 1)
        return theta
    end

    model = combined(STAN_SOURCE, 0.4)
    sampled_parameters = model()
    rand_parameters = NamedTuple(rand(model)).theta
    @test sum(sampled_parameters[1:3]) ≈ 1
    @test sampled_parameters[4] > 0
    @test norm(sampled_parameters[5:6]) ≈ 1
    @test sampled_parameters[7] > 0
    @test sum(sampled_parameters[8:9]) ≈ 1
    @test length(rand_parameters) == length(distribution)
    @test insupport(distribution, rand_parameters)
    expected_unlinked =
        logpdf(distribution, constrained) + logpdf(Normal(constrained[1], 1), 0.4)
    @test logjoint(model, (; theta=constrained)) ≈ expected_unlinked

    conditioned_model = condition(model, (; theta=constrained))
    @test logjoint(conditioned_model, NamedTuple()) ≈ expected_unlinked

    ldf = LogDensityFunction(model)
    value = LogDensityProblems.logdensity(ldf, u)
    gradient = ForwardDiff.gradient(u -> LogDensityProblems.logdensity(ldf, u), u)
    _, stan_gradient = BridgeStan.log_density_gradient(
        distribution.transform.model, u; propto=false, jacobian=true
    )
    downstream_gradient = ForwardDiff.gradient(u) do u
        return logpdf(Normal(distribution.transform(u)[1], 1), 0.4)
    end
    @test value ≈
        BridgeStan.log_density(
        distribution.transform.model, u; propto=false, jacobian=true
    ) + logpdf(Normal(constrained[1], 1), 0.4)
    @test isfinite(value)
    @test gradient ≈ stan_gradient + downstream_gradient
    uniform_u = rand(ldf, InitFromUniform())
    @test length(uniform_u) == length(u)
    @test all(-2 .<= uniform_u .<= 2)

    mooncake_ldf = LogDensityFunction(
        model, getlogjoint_internal, LinkAll(); adtype=AutoMooncake(; config=nothing)
    )
    mooncake_value, mooncake_gradient = LogDensityProblems.logdensity_and_gradient(
        mooncake_ldf, u
    )
    @test mooncake_value ≈ value
    @test mooncake_gradient ≈ gradient
end

@testset "BridgeStan generated parameter types" begin
    distribution = to_distribution(STAN_PARAMETER_TYPES; data="{\"K\": 2}")
    n = Bijectors.VectorBijectors.linked_vec_length(distribution)
    u = collect(range(0.1, 0.5; length=n))
    du = collect(range(-0.2, 0.3; length=n))
    constrained = distribution.transform(u)
    cotangent = collect(range(0.4, -0.1; length=length(constrained)))
    step = 1e-6

    _, (jvp,) = DynamicPPL._stan_value_and_pushforward(distribution.transform, u, (du,))
    _, (vjp,) = DynamicPPL._stan_value_and_pullback(distribution.transform, u, (cotangent,))
    finite_difference_jvp =
        (distribution.transform(u + step * du) - distribution.transform(u - step * du)) /
        (2 * step)
    finite_difference_vjp = map(eachindex(u)) do index
        direction = zeros(n)
        direction[index] = step
        return cotangent' * (
            distribution.transform(u + direction) - distribution.transform(u - direction)
        ) / (2 * step)
    end

    @test all(isfinite, constrained)
    canonical_u = Bijectors.VectorBijectors.to_linked_vec(distribution)(constrained)
    @test distribution.transform(canonical_u) ≈ constrained
    @test norm(jvp - finite_difference_jvp) < 1e-7
    @test norm(vjp - finite_difference_vjp) < 1e-7
end

@testset "BridgeStan parameter-free model and compiler flags" begin
    distribution = to_distribution(
        STAN_NO_PARAMETERS;
        data="{\"observation\": 0.2}",
        stanc_args=["--O1"],
        make_args=["STAN_THREADS=true"],
    )
    u = Float64[]
    _, (jvp,) = DynamicPPL._stan_value_and_pushforward(distribution.transform, u, (u,))
    _, (vjp,) = DynamicPPL._stan_value_and_pullback(distribution.transform, u, (u,))

    @test length(distribution) == 0
    @test insupport(distribution, u)
    @test isfinite(logpdf(distribution, u))
    @test isempty(distribution.transform(u))
    @test isempty(jvp)
    @test isempty(vjp)
end

@testset "BridgeStan constrained parameter without free coordinates" begin
    distribution = to_distribution(STAN_NO_FREE_PARAMETERS)
    u = Float64[]
    constrained = distribution.transform(u)
    _, (jvp,) = DynamicPPL._stan_value_and_pushforward(distribution.transform, u, (u,))
    _, (vjp,) = DynamicPPL._stan_value_and_pullback(distribution.transform, u, (ones(1),))
    unconstrain = Bijectors.VectorBijectors.to_linked_vec(distribution)
    _, (unconstrain_jvp,) = DynamicPPL._stan_value_and_pushforward(
        unconstrain, constrained, (ones(1),)
    )
    _, (unconstrain_vjp,) = DynamicPPL._stan_value_and_pullback(
        unconstrain, constrained, (u,)
    )

    @test constrained == [1.0]
    @test jvp == [0.0]
    @test isempty(vjp)
    @test isempty(unconstrain_jvp)
    @test unconstrain_vjp == [0.0]
    @test logpdf(distribution, constrained) == 0
end

end
