module DynamicPPLBridgeStanExtTests

using ADTypes: AutoForwardDiff, AutoMooncake
using BridgeStan
using DifferentiationInterface
using Distributions: Normal, logpdf
using DynamicPPL
using ForwardDiff
using LinearAlgebra: norm
using LogDensityProblems
using Mooncake
using Test

const BridgeStanExt = Base.get_extension(DynamicPPL, :DynamicPPLBridgeStanExt)

const STAN_SOURCE = """
parameters {
  simplex[3] theta;
  real<lower=0> sigma;
  unit_vector[2] direction;
  tuple(real<lower=0>, simplex[2]) pair;
}
model {
  theta ~ dirichlet(rep_vector(1, 3));
  sigma ~ exponential(1);
}
generated quantities {
  real draw = normal_rng(sigma, 1);
}
"""

const STAN_PARAMETER_TYPES = """
data {
  int<lower=2> K;
}
transformed data {
  real limit = 2;
}
parameters {
  real plain;
  real<lower=0> lower_real;
  real<upper=1> upper_real;
  real<lower=-1, upper=1> bounded_real;
  real<offset=1> offset_real;
  real<multiplier=2> scaled_real;
  real<offset=1, multiplier=2> affine_real;
  real<lower=-limit, upper=limit> data_bounded_real;
  vector[K] plain_vector;
  vector<lower=0>[K] lower_vector;
  vector<upper=1>[K] upper_vector;
  vector<lower=-1, upper=1>[K] bounded_vector;
  vector<offset=1>[K] offset_vector;
  vector<multiplier=2>[K] scaled_vector;
  vector<offset=1, multiplier=2>[K] affine_vector;
  row_vector[K] plain_row_vector;
  row_vector<lower=0>[K] lower_row_vector;
  row_vector<upper=1>[K] upper_row_vector;
  row_vector<lower=-1, upper=1>[K] bounded_row_vector;
  row_vector<offset=1>[K] offset_row_vector;
  row_vector<multiplier=2>[K] scaled_row_vector;
  row_vector<offset=1, multiplier=2>[K] affine_row_vector;
  matrix[K, K] plain_matrix;
  matrix<lower=0>[K, K] lower_matrix;
  matrix<upper=1>[K, K] upper_matrix;
  matrix<lower=-1, upper=1>[K, K] bounded_matrix;
  matrix<offset=1>[K, K] offset_matrix;
  matrix<multiplier=2>[K, K] scaled_matrix;
  matrix<offset=1, multiplier=2>[K, K] affine_matrix;
  ordered[K] ordered_parameter;
  positive_ordered[K] positive_ordered_parameter;
  simplex[K] simplex_parameter;
  unit_vector[K] unit_vector_parameter;
  sum_to_zero_vector[K] zero_sum_vector;
  column_stochastic_matrix[K, K] column_stochastic_parameter;
  row_stochastic_matrix[K, K] row_stochastic_parameter;
  sum_to_zero_matrix[K, K] zero_sum_matrix;
  corr_matrix[K] correlation_parameter;
  cov_matrix[K] covariance_parameter;
  cholesky_factor_corr[K] correlation_cholesky;
  cholesky_factor_cov[K] covariance_cholesky;
  cholesky_factor_cov[K + 1, K] rectangular_covariance_cholesky;
  complex complex_parameter;
  complex_vector[K] complex_vector_parameter;
  complex_row_vector[K] complex_row_vector_parameter;
  complex_matrix[K, K] complex_matrix_parameter;
  array[2, 2] simplex[K] simplex_array;
  tuple(real<lower=0>, array[2] real, tuple(simplex[K], complex)) nested_tuple;
  array[2] tuple(array[2] real, tuple(simplex[K], real)) tuple_array;
  vector[0] empty_vector;
  array[0] real empty_array;
}
transformed parameters {
  real transformed_parameter = 2 * plain;
}
model {
  plain ~ normal(0, 1);
}
generated quantities {
  real draw = normal_rng(transformed_parameter, 1);
}
"""

const STAN_NO_PARAMETERS = """
data {
  real observation;
}
model {
  observation ~ normal(0, 1);
}
"""

@testset "BridgeStan extension" begin
    @test_throws ErrorException BridgeStanExt._parameter_writer("")
    @test_logs (:warn, r"Could not determine") BridgeStanExt._warn_untested_versions("")
    @test_logs (:warn, r"supports Stan 2.39.x") BridgeStanExt._warn_untested_versions(
        "// Code generated by stanc v2.40.0"
    )

    distribution = to_distribution(STAN_SOURCE)
    @test to_distribution(STAN_SOURCE) === distribution
    u = [0.3, -0.7, 0.2, 0.4, -0.1, 0.5, -0.2]
    du = [-0.2, 0.5, 0.3, -0.1, 0.2, 0.4, -0.3]
    cotangent = [1.2, -0.4, 0.8, 0.1, -0.2, 0.7, 0.3, -0.1, 0.6]
    step = 1e-6

    constrained = distribution.transform(u)
    finite_difference_jvp =
        (distribution.transform(u + step * du) - distribution.transform(u - step * du)) /
        (2 * step)
    finite_difference_vjp = map(eachindex(u)) do index
        direction = zeros(length(u))
        direction[index] = step
        return cotangent' * (
            distribution.transform(u + direction) - distribution.transform(u - direction)
        ) / (2 * step)
    end
    _, (jvp,) = DynamicPPL._stan_value_and_pushforward(distribution.transform, u, (du,))
    _, (vjp,) = DynamicPPL._stan_value_and_pullback(distribution.transform, u, (cotangent,))

    @test length(distribution) == length(u)
    @test length(constrained) == length(cotangent)
    @test norm(constrained[5:6]) ≈ 1
    @test constrained[7] > 0
    @test sum(constrained[8:9]) ≈ 1
    @test norm(jvp - finite_difference_jvp) < 1e-8
    @test norm(vjp - finite_difference_vjp) < 1e-8
    @test ForwardDiff.gradient(x -> logpdf(distribution, x), u) isa Vector{Float64}
    @test ForwardDiff.jacobian(distribution.transform, u) * du ≈ jvp

    @model function combined(stan, y)
        theta ~ to_distribution(stan)
        y ~ Normal(theta[1], 1)
        return theta
    end

    model = combined(STAN_SOURCE, 0.4)
    sampled_parameters = model()
    @test sum(sampled_parameters[1:3]) ≈ 1
    @test sampled_parameters[4] > 0
    @test norm(sampled_parameters[5:6]) ≈ 1
    @test sampled_parameters[7] > 0
    @test sum(sampled_parameters[8:9]) ≈ 1

    ldf = LogDensityFunction(model; adtype=AutoForwardDiff())
    value, gradient = LogDensityProblems.logdensity_and_gradient(ldf, u)
    @test isfinite(value)
    @test all(isfinite, gradient)

    mooncake_ldf = LogDensityFunction(model; adtype=AutoMooncake(; config=nothing))
    mooncake_value, mooncake_gradient = LogDensityProblems.logdensity_and_gradient(
        mooncake_ldf, u
    )
    @test mooncake_value ≈ value
    @test mooncake_gradient ≈ gradient
end

@testset "BridgeStan generated parameter types" begin
    distribution = to_distribution(STAN_PARAMETER_TYPES; data="{\"K\": 2}")
    n = length(distribution)
    u = collect(range(0.1, 0.5; length=n))
    du = collect(range(-0.2, 0.3; length=n))
    constrained = distribution.transform(u)
    cotangent = collect(range(0.4, -0.1; length=length(constrained)))
    step = 1e-6

    _, (jvp,) = DynamicPPL._stan_value_and_pushforward(distribution.transform, u, (du,))
    _, (vjp,) = DynamicPPL._stan_value_and_pullback(distribution.transform, u, (cotangent,))
    finite_difference_jvp =
        (distribution.transform(u + step * du) - distribution.transform(u - step * du)) /
        (2 * step)
    finite_difference_vjp = map(eachindex(u)) do index
        direction = zeros(n)
        direction[index] = step
        return cotangent' * (
            distribution.transform(u + direction) - distribution.transform(u - direction)
        ) / (2 * step)
    end

    @test all(isfinite, constrained)
    @test norm(jvp - finite_difference_jvp) < 1e-7
    @test norm(vjp - finite_difference_vjp) < 1e-7
end

@testset "BridgeStan parameter-free model and compiler flags" begin
    distribution = to_distribution(
        STAN_NO_PARAMETERS;
        data="{\"observation\": 0.2}",
        stanc_args=["--O1"],
        make_args=["STAN_THREADS=true"],
    )
    u = Float64[]
    _, (jvp,) = DynamicPPL._stan_value_and_pushforward(distribution.transform, u, (u,))
    _, (vjp,) = DynamicPPL._stan_value_and_pullback(distribution.transform, u, (u,))

    @test isempty(distribution.transform(u))
    @test isempty(jvp)
    @test isempty(vjp)
end

end
