name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
  merge_group:
    types: [checks_requested]

concurrency:
  # All documentation workflows write to the same gh-pages branch.
  group: docs-gh-pages
  queue: max

permissions:
  contents: write
  pull-requests: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Build and deploy Documenter.jl docs
        uses: TuringLang/actions/DocsDocumenter@main
