name: DynamicPPL-CI

on:
  push:
    branches:
      # This is where pull requests from "bors r+" are built.
      - staging
      # This is where pull requests from "bors try" are built.
      - trying
      # Build the master branch.
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.version == 'nightly' }}
    strategy:
      matrix:
        version:
          - '1.3'
          - '1'
          # - 'nightly'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x86
          - x64
        exclude:
          - os: windows-latest
            arch: x86
          - os: macOS-latest
            arch: x86
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
